######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 15 19:53:43 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
