######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 30 21:13:49 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
