######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 4 12:18:49 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
